export const  REFRESH_ARTICLE_DOING = "REFRESH_ARTICLE_DOING"
export const  REFRESH_ARTICLE_DONE = "REFRESH_ARTICLE_DONE"
export const  COLLECT_ARTICLE = "COLLECT_ARTICLE"
export const  CHANGE_ARTICLE = "CHANGE_ARTICLE"

export const SAGA_TODAY_ARTICLE = "SAGA_TODAY_ARTICLE"
export const SAGA_PREV_ARTICLE = "SAGA_PREV_ARTICLE"
export const SAGA_NEXT_ARTICLE = "SAGA_NEXT_ARTICLE"
export const SAGA_RANDOM_ARTICLE = "SAGA_RANDOM_ARTICLE"

export const SPLASH_SHOW = "SPLASH_SHOW"
export const SPLASH_HIDE = "SPLASH_HIDE"

//settings
export const FONT_SIZE_SMALL = "FONT_SIZE_SMALL"
export const FONT_SIZE_MIDDLE = "FONT_SIZE_MIDDLE"
export const FONT_SIZE_LARGE = "FONT_SIZE_LARGE"

export const MAIN_BG_1 = "MAIN_BG_1"
export const MAIN_BG_2 = "MAIN_BG_2"
export const MAIN_BG_3 = "MAIN_BG_3"
export const MAIN_BG_4 = "MAIN_BG_4"

export const CHANGE_MODEL = "CHANGE_MODEL"